DBMiddlewareの実装
atEaE/dosh pull request #1
Opened 2020-10-19 07:23 UTC by dW-t

# 概要
DBMiddlewareの実装

# Request分類
- [x] 機能追加・変更 (互換性のある機能追加・変更)

# チェックリスト
行った変更をチェックリストとして、下記に追加してください。
- [ ] DB接続の最低限の実装

2020-10-19 07:45 UTC, atEaE requested changes
レビューしました。

2020-10-19 07:45 UTC, atEaE commented on Dosh.Middleware.DB/Middleware/Context/DBContext.cs
> +    public static class DBContext
ネーミングだけど、今回はEFCoreみたいなのを使ってないから、DBClientの方がしっくりくるかなと思いました。
EFを使っている場合は、EFがDBや設定のContext情報(背景情報)を全部持っているから、DBContextでもよいけど、
今回は自前で接続して、接続したとしてもDBの情報は何も知らない状態だから、DBClientの方がよいかなと。

2020-10-19 07:45 UTC, atEaE commented on Dosh.Middleware.DB/Middleware/Context/DBContext.cs
> +                    Console.WriteLine("Exception.Message: {0}", ex.Message);
ここら辺のLogは、最終的にResource.resxから出力されると思っていてOK？

2020-10-19 07:45 UTC, atEaE commented on Tests/Test_Dosh.Middleware.DB/Middleware/Context/Test_DBContext.cs
> +        private string ConnectionString = "data source=(localdb)\\SALDB01T;initial catalog=DB01TD01;user id=SOALA;password=BGT56yhn;";
接続情報は、共有したyamlの形式で渡ってくるから、ConnectionStringBuilderがいると良いと思います。
(既存でも、ConnectionStringBuilderがいた気がします！)

2020-10-20 02:39 UTC, dW-t commented on Dosh.Middleware.DB/Middleware/Context/DBContext.cs
> +    public static class DBContext
修正しました。

2020-10-20 02:40 UTC, dW-t commented on Dosh.Middleware.DB/Middleware/Context/DBContext.cs
> +                    Console.WriteLine("Exception.Message: {0}", ex.Message);
はい。Crawler実装の際に修正予定です。

2020-10-20 02:41 UTC, dW-t commented on Tests/Test_Dosh.Middleware.DB/Middleware/Context/Test_DBContext.cs
> +        private string ConnectionString = "data source=(localdb)\\SALDB01T;initial catalog=DB01TD01;user id=SOALA;password=BGT56yhn;";
ConnectionStringクラス作成し、今後typeごとにConnectionString作成できるよう修正しました！

2020-10-20 04:28 UTC, atEaE reviewed
PR確認しました。マージします！

2020-10-20 04:29 UTC, merged